# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Default left prompt ...
format = """$all"""

# ... except a few modules moved to the right
right_format = """
$status\
$cmd_duration\
$battery\
$time
"""

# Inserts a blank line between shell prompts
add_newline = true


palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[username]
disabled = true

[hostname]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = '…/'
fish_style_pwd_dir_length = 1

[status]
disabled = false
#format = '[$symbol$status]($style) '
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
symbol = '🔴 '

[time]
disabled = false

[kubernetes]
disabled = false
detect_files = ['kustomization.yaml', 'kustomization.yml']
detect_folders = ['overlays']

[azure]
disabled = false

[vagrant]
# Remove vagrant version
version_format = ''
# vagrant takes ~100ms under WSL
disabled = true
