---
- name: Install and configure tmux & tools
  ansible.builtin.import_role:
    name: _base_app
  vars:
    packages_pacman:
      - tmux
      - tmuxp
    packages_aur:
      - sesh-bin
    packages_apt:
      - tmux
      - tmuxp
    pre_stow_folders: []
    packages_stow:
      - tmux
      - tmuxp
      - sesh

- name: Git checkout TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tpm_dir }}"
  notify: Install TPM plugins

- name: Install tmux tools (Ubuntu)
  ansible.builtin.include_tasks: tasks_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
