---
- name: Install k9s from the Github releases
  ansible.builtin.apt:
    deb: https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide_{{ zoxide_version }}-1_amd64.deb
  become: yes
