[misc]
# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
pre_sudo = true

# Disable specific steps - same options as the command line flag
disable = [
    "gcloud",     # Usually installed via the system packet manager
    "containers", # Too many failures for local/private images, and not useful enough
]

# Run specific steps - same options as the command line flag
# only = ["system", "emacs"]

# Whether to self update
# this will be ignored if the binary is built without self update support
# available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
no_self_update = true

# Do not set the terminal title (default: true)
set_title = false

# Cleanup temporary or old files (default: false)
cleanup = true

[git]
# Additional git repositories to pull
repos = [
    "~/.*/",            # Include repos like ~/.pyenv, ~/.tfenv, ...
    "~/.zsh/plugins/*", # Include zsh plugins
]

# Don't pull the predefined git repos
# pull_predefined = false

[post_commands]
"Regenerate ZSH completions" = "zsh ${HOME}/.config/zsh/scripts/completion-cache-generator.zsh"
