[misc]
# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
pre_sudo = true

# Disable specific steps - same options as the command line flag
disable = [
    "gcloud", # Usually installed via the system packet manager
]

# Run specific steps - same options as the command line flag
# only = ["system", "emacs"]

# Whether to self update
# this will be ignored if the binary is built without self update support
# available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
no_self_update = true

# Do not set the terminal title (default: true)
set_title = false

# Cleanup temporary or old files (default: false)
cleanup = true

[git]
# Additional git repositories to pull
repos = [
    "~/.*/",            # Include repos like ~/.pyenv, ~/.tfenv, ...
    "~/.zsh/plugins/*", # Include zsh plugins
]

# Don't pull the predefined git repos
# pull_predefined = false

# containers = ["archlinux-latest"]
[containers]
# Specify the containers to ignore while updating (Wildcard supported)
# ignored_containers = ["ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest", "docker.io*"]
# Specify the runtime to use for containers (default: "docker", allowed values: "docker", "podman")
# runtime = "podman"

[post_commands]
"Regenerate ZSH completions" = "zsh ${HOME}/.config/zsh/scripts/completion-cache-generator.zsh"
